// demoPkg/vue/src/App.vue
<script setup lang="ts">
import { MonacoEditor, MonacoDiffEditor } from '../../../src/vue/index'
import type { MonacoCodeEditorLanguage, MonacoCodeEditorTheme, MonacoEditorOptions, Monaco } from '../../../src/vue/index'
import { ref } from 'vue'
import { NInput, NSelect, NSpace } from 'naive-ui'
import "./useWorker"
import { MonacoCodeEditor } from '../../../src/type';

const languages: MonacoCodeEditorLanguage[] = [
  'css',
  'dart',
  'dockerfile',
  'go',
  'graphql',
  'html',
  'java',
  'javascript',
  'json',
  'kotlin',
  'less',
  'markdown',
  'mdx',
  'mysql',
  'objective-c',
  'pgsql',
  'php',
  'powershell',
  'protobuf',
  'python',
  'redis',
  'ruby',
  'rust',
  'scala',
  'scheme',
  'scss',
  'shell',
  'sql',
  'swift',
  'typescript',
  'xml',
  'yaml',
]
const themes: MonacoCodeEditorTheme[] = ['vs', 'vs-dark', 'hc-black', 'hc-light']

const input = ref('const a = 123;')
const language = ref<MonacoCodeEditorLanguage>('javascript')
const languageOptions = languages.map((item) => ({ label: item, value: item }))
const theme = ref('vs-dark')
const themeOptions = themes.map((item) => ({ label: item, value: item }))
const width = ref('300')
const height = ref('600')
const options = ref<MonacoEditorOptions>({
  lineNumbers: 'off',
  folding: false,
  glyphMargin: false,
  lineDecorationsWidth: 0,
  lineNumbersMinChars: 0,
})
const handleUpdateOptions = (newOptions: string) => {
  try {
    options.value = JSON.parse(newOptions)
  } catch (error) {
    console.log('error', error)
  }
}
const monacoEditor = ref<MonacoCodeEditor | null>(null)

const updateMonacoEditor = (editor: MonacoCodeEditor, monaco: Monaco) => {
  monacoEditor.value = editor
  console.log('editor', editor)
}
</script>

<template>
  <NSpace style="padding: 20px;">
    <div class="left">
      <div>
        <span>language</span>
        <NSelect :options='languageOptions' v-model:value="language" filterable />
      </div>
      <div>
        <span>theme</span>
        <NSelect :options='themeOptions' v-model:value="theme" filterable />
      </div>
      <div>
        <span>width</span>
        <NInput placeholder="Input width" v-model:value="width" />
      </div>
      <div>
        <span>height</span>
        <NInput placeholder="Input height" v-model:value="height" />
      </div>
      <div>
        <span>options</span>
        <MonacoEditor :value="JSON.stringify(options, null, 2)" @update:value="handleUpdateOptions" language="json"
          width="300" height="200" :options="options" />
      </div>
    </div>
    <MonacoEditor v-model:value="input" :theme="theme" :width="width" :language="language" :height="height"
      :options="options" ref="monacoEditorRef" :onEditorWillMount="(monaco: Monaco) => {
        return {
          lineNumbers: 'on',
          folding: true,
          glyphMargin: true,
        }
      }" :onEditorDidMount="updateMonacoEditor" />
    <MonacoDiffEditor v-model:value="input" originalValue="const a = 12;" :theme="theme" :width="width"
      :language="language" :height="height" :options="options" :onEditorWillMount="(monaco: Monaco) => {
        return {
          glyphMargin: true,
        }
      }" />
  </NSpace>
</template>

<style>
</style>

// demoPkg/react/src/App.tsx
import { SelectValue } from '@radix-ui/react-select'
import type {
  Monaco,
  MonacoCodeEditorLanguage,
  MonacoCodeEditorTheme,
  MonacoEditorOptions,
  MonacoEditorRef,
} from 'monaco-editor-component/react'
import { MonacoDiffEditor, MonacoEditor } from 'monaco-editor-component/react'
import { useRef, useState } from 'react'
import { Select, SelectContent, SelectItem, SelectTrigger } from '@/components/ui/select'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import './useWorker'

const languages: MonacoCodeEditorLanguage[] = [
  'css',
  'dart',
  'dockerfile',
  'go',
  'graphql',
  'html',
  'java',
  'javascript',
  'json',
  'kotlin',
  'less',
  'markdown',
  'mdx',
  'mysql',
  'objective-c',
  'pgsql',
  'php',
  'powershell',
  'protobuf',
  'python',
  'redis',
  'ruby',
  'rust',
  'scala',
  'scheme',
  'scss',
  'shell',
  'sql',
  'swift',
  'typescript',
  'xml',
  'yaml',
]
const themes: MonacoCodeEditorTheme[] = ['vs', 'vs-dark', 'hc-black', 'hc-light']
/**
 *
 */
function App() {
  const [input, setInput] = useState('')
  const [language, setLanguage] = useState<MonacoCodeEditorLanguage>('javascript')
  const [theme, setTheme] = useState<MonacoCodeEditorTheme>('vs-dark')
  const [width, setWidth] = useState('500')
  const [height, setHeight] = useState('600')
  const [options, setOptions] = useState<MonacoEditorOptions>({
    lineNumbers: 'off',
    folding: false,
    glyphMargin: false,
    lineDecorationsWidth: 0,
    lineNumbersMinChars: 0,
  })
  const editor = useRef<MonacoEditorRef>(null)

  console.log('editor', editor)
  setTimeout(() => {
    console.log('editor', editor.current?.editor.current)
  }, 2000)
  return (
    <div className="flex flex-col h-screen App">
      <h1 className="flex justify-center mt-4 font-bold">Monaco Editor Demo</h1>
      <div className="flex gap-6 p-10">
        <div className="options flex h-[800px] flex-col gap-2">
          <div className="language">
            <Label>language</Label>
            <Select value={language} onValueChange={(newValue: MonacoCodeEditorLanguage) => setLanguage(newValue)}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="Please Select" />
              </SelectTrigger>
              <SelectContent>
                {languages?.map((language, index) => (
                  <SelectItem key={index} value={language}>
                    {language}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="theme">
            <Label>theme</Label>
            <Select value={theme} onValueChange={(newValue: MonacoCodeEditorTheme) => setTheme(newValue)}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="Please Select" />
              </SelectTrigger>
              <SelectContent>
                {themes?.map((theme, index) => (
                  <SelectItem key={index} value={theme}>
                    {theme}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="width">
            <Label>width</Label>
            <Input
              value={width}
              onChange={(e) => {
                setWidth(e.target.value)
              }}
            />
          </div>
          <div className="height">
            <Label>height</Label>
            <Input
              value={height}
              onChange={(e) => {
                setHeight(e.target.value)
              }}
            />
          </div>
          <div className="options">
            <Label>options</Label>
            <MonacoEditor
              value={JSON.stringify(options, null, 2)}
              onChange={(newVal) => {
                console.log('xxxx', newVal)
                try {
                  setOptions(JSON.parse(newVal))
                }
                catch (error) {
                  console.log('error', error)
                }
              }}
              language="json"
              width={300}
              height={200}
              options={options}
            />
          </div>
        </div>
        <div>
          <Label>Monaco Editor</Label>
          <MonacoEditor
            value={input}
            onChange={(newVal) => {
              setInput(newVal)
            }}
            ref={editor}
            language={language}
            theme={theme}
            className="flex ml-4"
            width={width}
            height={height}
            options={options}
            // @typescript-eslint/no-unused-vars
            onEditorWillMount={(monaco: Monaco) => {
              return {
                lineNumbers: 'on',
                folding: true,
                glyphMargin: true,
              }
            }}
          />
        </div>
        <div>
          <Label>Monaco Diff Editor</Label>
          <MonacoDiffEditor
            value={input}
            originalValue="const a = 1;"
            language={language}
            theme={theme}
            onChange={(newValue) => {
              setInput(newValue)
            }}
            options={options}
            width={width}
            height={height}
            onEditorWillMount={() => {
              return {
                glyphMargin: true,
              }
            }}
          />
        </div>
      </div>
    </div>
  )
}

export default App
